# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da35e7be647aa7dac00024dae162f5a458bacecd063d436b747834a74d7585e2114917d6b8615edf7aa76304b5a55dde65f551f69c92ae0b5bb3cbc1dfb4d10a

test:
  secret_key_base: 489dcf0d8c78a78f95f00ed61a4236c82ede0ec6f6c5ce1be24279f5aa33cfcfbbe861f76460502c7fad9335d45d8428cf0c0f9be3a523fca1aec0cf7578d0fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
